### ISSUE TITLE
Can we get one that extracts WiFi password ?

### ISSUE THREAD

**Issue by minanagehsalalma** [KINGSABRI/godofwar#1]
Just like this one 
https://milo2012.wordpress.com/2012/03/11/hacking-beyond-the-browser-with-beef-robbing-your-wireless-keys/

But better and works with modern systems

**Comment by KINGSABRI** [comment]
Hi @minanagehsalalma 

I'm not sure really how this related to this tool

**Comment by minanagehsalalma** [comment]
Cause the article uses java apleats and your tools use java too ?!

**Comment by KINGSABRI** [comment]
sorry not related
